# Lab 96 — App Gateway SSL termination with a self-signed cert in Key Vault.
# The cert never sits in the repo. Pieces:
#  - Key Vault + an access policy for you and for the App Gateway's identity.
#  - A self-signed cert GENERATED BY Key Vault (issuer = Self), stored as PFX.
#  - A user-assigned identity granted Get on the cert secret.
#  - App Gateway v2 with that identity, an HTTPS listener (443), and an
#    ssl_certificate pointing at key_vault_secret_id. Browsers warn (self-signed).

# Terraform block: which Terraform CLI and provider versions this lab requires
# (random is needed for the unique Key Vault name suffix).
terraform {
  required_version = ">= 1.5.0"
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "~> 3.70"
    }

    random = {
      source  = "hashicorp/random"
      version = "~> 3.6"
    }
  }
}

# Provider block: configures azurerm against the subscription from `az login`.
# `features {}` is an empty settings block the azurerm provider requires.
provider "azurerm" {
  features {}
}

# Data source (read-only lookup): YOUR login's tenant + object id, used to
# grant the current user access to the Key Vault without hardcoding ids.
data "azurerm_client_config" "current" {}

# Root variable for the backend VM's admin SSH key (kept out of CLI output).
variable "admin_ssh_key" {
  type      = string
  sensitive = true
}

# Locals: named expressions computed once per run (not stored in state).
locals {
  cloud_init = <<-EOT
    #cloud-config
    package_update: true
    packages: [nginx]
    runcmd: [ "systemctl enable --now nginx" ]
  EOT
}

# A stateful random string. Unlike md5(timestamp()) this value is SAVED in
# Terraform state, so it only changes when the resource is destroyed —
# every plan/apply is stable and nothing gets unexpectedly replaced.
resource "random_string" "suffix" {
  length  = 6
  upper   = false
  special = false
}

resource "azurerm_resource_group" "this" {
  name     = "rg-appgw-ssl"
  location = "eastus"
}

# 1. Key Vault
# 1. Key Vault: stores the cert. The random suffix makes the globally-unique
# vault name reproducible (state-saved, so it does not change every apply).
resource "azurerm_key_vault" "this" {
  name                       = "kv-appgwssl-${random_string.suffix.result}"
  location                   = azurerm_resource_group.this.location
  resource_group_name        = azurerm_resource_group.this.name
  tenant_id                  = data.azurerm_client_config.current.tenant_id
  sku_name                   = "standard"
  soft_delete_retention_days = 7
  purge_protection_enabled   = false
}

# Access policy: current user can manage secrets/certs.
# Access policy: current user can manage secrets/certs (needed to CREATE the cert).
resource "azurerm_key_vault_access_policy" "user" {
  key_vault_id            = azurerm_key_vault.this.id
  tenant_id               = data.azurerm_client_config.current.tenant_id
  object_id               = data.azurerm_client_config.current.object_id
  secret_permissions      = ["Get", "List", "Set", "Delete", "Purge"]
  certificate_permissions = ["Get", "List", "Create", "Delete", "Purge"]
}

# 3. User-assigned identity for the App Gateway to read the cert.
resource "azurerm_user_assigned_identity" "appgw" {
  name                = "id-appgw-ssl"
  location            = azurerm_resource_group.this.location
  resource_group_name = azurerm_resource_group.this.name
}

# Grant the App Gateway identity Get on secrets.
resource "azurerm_key_vault_access_policy" "appgw" {
  key_vault_id            = azurerm_key_vault.this.id
  tenant_id               = data.azurerm_client_config.current.tenant_id
  object_id               = azurerm_user_assigned_identity.appgw.principal_id
  secret_permissions      = ["Get"]
  certificate_permissions = ["Get"]
}

# 2. Self-signed cert generated by Key Vault itself, stored as PFX.
# 2. Self-signed cert generated by Key Vault itself, stored as PFX.
# Note the depends_on: the vault must already grant the current user access
# before Terraform tries to create a certificate in it.
resource "azurerm_key_vault_certificate" "this" {
  name         = "appgw-ssl-cert"
  key_vault_id = azurerm_key_vault.this.id

  certificate_policy {
    issuer_parameters {
      name = "Self"
    }
    key_properties {
      exportable = true
      key_size   = 2048
      key_type   = "RSA"
      reuse_key  = false
    }
    secret_properties {
      content_type = "application/x-pkcs12"
    }
    x509_certificate_properties {
      subject            = "CN=appgw-ssl.local"
      validity_in_months = 12
      key_usage          = ["digitalSignature", "keyEncipherment"]
    }
  }

  depends_on = [azurerm_key_vault_access_policy.user]
}

# Network: VNet + appgw subnet (gateway-only) + backend subnet + 1 nginx VM.
resource "azurerm_virtual_network" "this" {
  name                = "vnet-appgw-ssl"
  location            = azurerm_resource_group.this.location
  resource_group_name = azurerm_resource_group.this.name
  address_space       = ["172.25.0.0/20"]
}

resource "azurerm_subnet" "appgw" {
  name                 = "snet-appgw"
  resource_group_name  = azurerm_resource_group.this.name
  virtual_network_name = azurerm_virtual_network.this.name
  address_prefixes     = ["172.25.0.0/26"]
}

resource "azurerm_subnet" "backend" {
  name                 = "snet-backend"
  resource_group_name  = azurerm_resource_group.this.name
  virtual_network_name = azurerm_virtual_network.this.name
  address_prefixes     = ["172.25.0.64/26"]
}

resource "azurerm_network_interface" "backend" {
  name                = "nic-appgw-ssl-be"
  location            = azurerm_resource_group.this.location
  resource_group_name = azurerm_resource_group.this.name
  ip_configuration {
    name                          = "ipconfig"
    subnet_id                     = azurerm_subnet.backend.id
    private_ip_address_allocation = "Dynamic"
  }
}

resource "azurerm_linux_virtual_machine" "backend" {
  name                  = "vm-appgw-ssl-be"
  location              = azurerm_resource_group.this.location
  resource_group_name   = azurerm_resource_group.this.name
  size                  = "Standard_B1s"
  admin_username        = "azureadmin"
  network_interface_ids = [azurerm_network_interface.backend.id]
  custom_data           = base64encode(local.cloud_init)
  admin_ssh_key {
    username   = "azureadmin"
    public_key = var.admin_ssh_key
  }
  os_disk {
    caching              = "ReadWrite"
    storage_account_type = "StandardSSD_LRS"
  }
  source_image_reference {
    publisher = "Canonical"
    offer     = "0001-com-ubuntu-server-jammy"
    sku       = "22_04-lts-gen2"
    version   = "latest"
  }
}

# The public IP clients browse to over HTTPS.
resource "azurerm_public_ip" "appgw" {
  name                = "pip-appgw-ssl"
  location            = azurerm_resource_group.this.location
  resource_group_name = azurerm_resource_group.this.name
  allocation_method   = "Static"
  sku                 = "Standard"
}

# 4. App Gateway with HTTPS listener + cert from Key Vault.
resource "azurerm_application_gateway" "this" {
  name                = "appgw-ssl"
  resource_group_name = azurerm_resource_group.this.name
  location            = azurerm_resource_group.this.location

  sku {
    name     = "Standard_v2"
    tier     = "Standard_v2"
    capacity = 1
  }

  # identity: the user-assigned identity above — how the gateway authenticates
  # to Key Vault to fetch the cert (no cert material ever passes through Terraform).
  identity {
    type         = "UserAssigned"
    identity_ids = [azurerm_user_assigned_identity.appgw.id]
  }

  gateway_ip_configuration {
    name      = "ipconfig"
    subnet_id = azurerm_subnet.appgw.id
  }

  # Port the gateway listens on: 443 (HTTPS) this time.
  frontend_port {
    name = "https"
    port = 443
  }

  frontend_ip_configuration {
    name                 = "fe"
    public_ip_address_id = azurerm_public_ip.appgw.id
  }

  # The cert is NOT a file here — just a reference to the Key Vault secret.
  ssl_certificate {
    name                = "cert"
    key_vault_secret_id = azurerm_key_vault_certificate.this.secret_id
  }

  backend_address_pool {
    name         = "be-default"
    ip_addresses = [azurerm_network_interface.backend.private_ip_address]
  }

  backend_http_settings {
    name                  = "http-settings"
    cookie_based_affinity = "Disabled"
    port                  = 80
    protocol              = "Http"
    request_timeout       = 60
  }

  # HTTPS listener: protocol Https + which ssl_certificate block to present.
  http_listener {
    name                           = "listener-https"
    frontend_ip_configuration_name = "fe"
    frontend_port_name             = "https"
    protocol                       = "Https"
    ssl_certificate_name           = "cert"
  }

  request_routing_rule {
    name                       = "rule"
    rule_type                  = "Basic"
    http_listener_name         = "listener-https"
    backend_address_pool_name  = "be-default"
    backend_http_settings_name = "http-settings"
    priority                   = 1
  }
}

# Open https://<ip> — the browser shows the self-signed cert warning, then
# the gateway terminates TLS and proxies plain HTTP to the nginx backend.
output "appgw_public_ip" { value = azurerm_public_ip.appgw.ip_address }
