# Lab 41 — Dynamic blocks.
# Teaches: `dynamic "security_rule" { for_each = ... content { ... } }` to stamp
# out repeated nested blocks from a variable, security_rule.value addressing, and
# a for expression in an output.
# A `dynamic` block generates a repeated NESTED block from a list/map. Perfect for
# NSG rules whose count/content you don't know at authoring time. Add a rule to
# tfvars and `terraform apply` extends the NSG without code changes.

# A list of rule objects. Each becomes one security_rule block.
variable "rules" {
  type = list(object({
    name     = string
    priority = number
    port     = number
  }))
  default = [
    { name = "Allow-HTTP", priority = 200, port = 80 },
    { name = "Allow-HTTPS", priority = 210, port = 443 },
  ]
}

# Resource group: the container that groups all resources for this lab in Azure.
resource "azurerm_resource_group" "this" {
  name     = "rg-dynamic"
  location = "eastus"
}

# ONE NSG resource, but its security_rule blocks are generated by `dynamic`.
# `security_rule` is the block label; for_each drives the count; security_rule.value
# is the current list element.
resource "azurerm_network_security_group" "this" {
  name                = "nsg-dynamic"
  location            = azurerm_resource_group.this.location
  resource_group_name = azurerm_resource_group.this.name

  dynamic "security_rule" {
    for_each = var.rules
    content {
      name                       = security_rule.value.name
      priority                   = security_rule.value.priority
      direction                  = "Inbound"
      access                     = "Allow"
      protocol                   = "Tcp"
      source_port_range          = "*"
      destination_port_range     = tostring(security_rule.value.port)
      source_address_prefix      = "*"
      destination_address_prefix = "*"
    }
  }
}

# Output: a for expression collecting just the names from the rules variable —
# one name per dynamic block that will be generated.
output "rule_names" {
  value = [for r in var.rules : r.name]
}
