# Lab 29 — for_each over a MAP of blobs.
# A map's values can be rich objects, not just strings. Here each blob has its
# own content. for_each iterates the map; each.key is the filename, each.value
# is the {content} object.

# locals: derived values for this lab — the storage-account name and the map of
# blobs that drives the for_each below.
locals {
  st = lower("stblobfe${random_string.suffix.result}")

  # A map keyed by filename → content. Each entry becomes one blob.
  # Keys with dots MUST be quoted, otherwise HCL reads them as references.
  files = {
    "readme.md" = "# Generated by Terraform\n"
    "app.json"  = "{\"version\":\"1.0\",\"env\":\"dev\"}"
    "note.txt"  = "remember to destroy me"
  }
}

# A stateful random string. Unlike md5(timestamp()) this value is SAVED in
# Terraform state, so it only changes when the resource is destroyed —
# every plan/apply is stable and nothing gets unexpectedly replaced.
resource "random_string" "suffix" {
  length  = 6
  upper   = false
  special = false
}

# Resource group: the container that groups all resources for this lab in Azure.
resource "azurerm_resource_group" "this" {
  name     = "rg-foreach-blobs"
  location = "eastus"
}

# Storage account: referencing azurerm_resource_group.this.name creates an
# implicit dependency, so Terraform always creates the group first.
resource "azurerm_storage_account" "this" {
  name                     = local.st
  resource_group_name      = azurerm_resource_group.this.name
  location                 = azurerm_resource_group.this.location
  account_tier             = "Standard"
  account_replication_type = "LRS"
}

# One ordinary container ("config") that the blobs below live in.
resource "azurerm_storage_container" "cfg" {
  name                  = "config"
  storage_account_name  = azurerm_storage_account.this.name
  container_access_type = "private"
}

# One blob per map entry. each.key = filename, each.value = content.
resource "azurerm_storage_blob" "file" {
  for_each               = local.files
  name                   = each.key
  storage_account_name   = azurerm_storage_account.this.name
  storage_container_name = azurerm_storage_container.cfg.name
  type                   = "Block"
  source_content         = each.value
}

# Output: keys() lists the map keys — the three uploaded filenames.
output "blobs" { value = keys(azurerm_storage_blob.file) }
